# ~/dotfiles/starship/.config/starship.toml

# Format for the prompt
format = """
$character$directory$git_branch$git_status$python
"""

# Directory module
[directory]
style = "bold cyan"
format = "[$path]($style) "

# Git branch module 
[git_branch]
format = "[git:](bold purple)[\\($branch\\)](bright-red) "
symbol = ""

# Git status module 
[git_status]
format = '([$all_status$ahead_behind]($style) )'
staged = "+"
modified = "!"
untracked = "?"
deleted = "✘"
style = "bold yellow"
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕${ahead_count}/${behind_count}"
conflicted = " ⚠"

# Python virtual environment (shows only when active)
[python]
style = "bold blue"
format = "([$virtualenv]($style) )"
disabled = false

# Prompt character
[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

