# ~/dotfiles/starship/.config/starship.toml

# Format for the prompt
format = """
$directory$git_branch$git_status$python$character
"""

# Directory module (cyan color)
[directory]
style = "bold cyan"
format = "[$path]($style) "

# Git branch module (rainbow-like colors)
[git_branch]
format = "[git:($branch)](bold purple) "
symbol = ""

# Git status module (showing an 'x' for changes)
[git_status]
format = "([✗](bold yellow) )"

# Python virtual environment (shows only when active)
[python]
style = "bold blue"
format = "([$virtualenv]($style) )"
disabled = false

# Prompt character
[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

